# Generated by Django 2.1 on 2018-08-13 10:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='unknown', max_length=255)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Timestamp of creation in the database.')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Timestamp of creation in the database.')),
            ],
        ),
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('unknown', 'unknown'), ('defined', 'defined'), ('created', 'created'), ('valid', 'valid'), ('copied', 'copied'), ('archived', 'archived'), ('secured', 'secured'), ('removed', 'removed')], default='unknown', max_length=20)),
                ('object', models.CharField(choices=[('observation', 'observation'), ('dataproduct', 'dataproduct')], default='dataproduct', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TaskObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=100)),
                ('task_type', models.CharField(choices=[('observation', 'observation'), ('dataproduct', 'dataproduct')], default='dataproduct', max_length=20)),
                ('taskID', models.CharField(blank=True, max_length=30, null=True, verbose_name='runId')),
                ('creationTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('new_status', models.CharField(choices=[('unknown', 'unknown'), ('defined', 'defined'), ('created', 'created'), ('valid', 'valid'), ('copied', 'copied'), ('archived', 'archived'), ('secured', 'secured'), ('removed', 'removed')], default='defined', max_length=20)),
                ('new_location', models.CharField(default='unknown', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DataProduct',
            fields=[
                ('taskobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='taskdatabase.TaskObject')),
                ('filename', models.CharField(default='unknown', max_length=200)),
                ('description', models.CharField(default='unknown', max_length=255)),
                ('dataproduct_type', models.CharField(choices=[('image', 'image'), ('cube', 'cube'), ('photometry', 'photometry'), ('spectrum', 'spectrum'), ('sed', 'sed'), ('timeSeries', 'timeseries'), ('visibility', 'visibility'), ('event', 'event'), ('catalog', 'catalog'), ('inspectionPlot', 'inspectionPlot')], default='visibility', max_length=50, verbose_name='type')),
                ('size', models.BigIntegerField(default=0)),
                ('quality', models.CharField(default='unknown', max_length=30)),
            ],
            bases=('taskdatabase.taskobject',),
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('taskobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='taskdatabase.TaskObject')),
                ('process_type', models.CharField(default='observation', max_length=50)),
                ('generatedDataProducts', models.ManyToManyField(blank=True, related_name='generatedByObservation', to='taskdatabase.DataProduct')),
            ],
            bases=('taskdatabase.taskobject',),
        ),
        migrations.AddField(
            model_name='taskobject',
            name='locations',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_location', to='taskdatabase.Location'),
        ),
        migrations.AddField(
            model_name='taskobject',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dataproduct_status', to='taskdatabase.Status'),
        ),
        migrations.AddField(
            model_name='taskobject',
            name='statusHistory',
            field=models.ManyToManyField(blank=True, related_name='dataproduct_status_history', to='taskdatabase.Status'),
        ),
        migrations.AddField(
            model_name='status',
            name='statusType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taskdatabase.StatusType'),
        ),
    ]
