# Generated by Django 2.1 on 2018-08-09 14:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=200)),
                ('type', models.CharField(choices=[('image', 'image'), ('cube', 'cube'), ('photometry', 'photometry'), ('spectrum', 'spectrum'), ('sed', 'sed'), ('timeSeries', 'timeseries'), ('visibility', 'visibility'), ('event', 'event'), ('catalog', 'catalog'), ('inspectionPlot', 'inspectionPlot')], default='visibility', max_length=50, verbose_name='type')),
                ('taskId', models.CharField(max_length=30, unique=True, verbose_name='runId')),
                ('creationTime', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Timestamp of creation in the database.')),
                ('size', models.BigIntegerField(default=0)),
                ('quality', models.CharField(default='unknown', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DataProductStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unknown', 'unknown'), ('defined', 'defined'), ('created', 'created'), ('valid', 'valid'), ('copied', 'copied'), ('archived', 'archived'), ('secured', 'secured'), ('removed', 'removed')], default='unknown', max_length=20)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Timestamp of creation in the database.')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='unknown', max_length=100)),
                ('path', models.CharField(default='unknown', max_length=255)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Timestamp of creation in the database.')),
            ],
        ),
        migrations.AddField(
            model_name='dataproduct',
            name='actual_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taskdatabase.DataProductStatus'),
        ),
        migrations.AddField(
            model_name='dataproduct',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taskdatabase.Location'),
        ),
        migrations.AddField(
            model_name='dataproduct',
            name='state_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_history', to='taskdatabase.DataProductStatus'),
        ),
    ]
